#!/bin/bash

if [ -r "`dirname "$0"`/gpg.conf" ]; then
  . "`dirname "$0"`/gpg.conf"
elif [ -r "`dirname "$0"`/../gpg.conf" ]; then
  . "`dirname "$0"`/../gpg.conf"
else
  exit 1
fi

FILENAME=$(gpg --list-packets "$1" | sed -e '/^:literal data packet:$/!d' \
    -e 'N' \
    -e 's/[^=]*name="//' \
    -e 's/",$//' \
    -e 'q')
if [ -z "$FILENAME" ]
then
  # Filename is empty
  FILENAME=$(sed 's/\.[^.]*$//' <<<$1)
fi
gpg --output "$FILENAME" --decrypt "$1" 1>> "$OUTPUT" 2>> "$OUTPUT"
_zenity_info "$?" "Unknown" "Unknown error"
zenity --info --title "GPG: Decrypt" --text "Successfully decrypted $1" --icon "$ZENITY_WINDOW_ICON"
