#!/bin/bash

# This script decrypts a file and opens it with the default editor.
# When the program that opened the file is closed, the file is
# checked for any changes.  If no changes have occured, the file
# is simply closed.  If changes occurred, then the file is
# re-encrypted.

if [ -r "`dirname "$0"`/gpg.conf" ]; then
  . "`dirname "$0"`/gpg.conf"
elif [ -r "`dirname "$0"`/../gpg.conf" ]; then
  . "`dirname "$0"`/../gpg.conf"
else
  exit 1
fi

# Look to see who the file was originally encrypted for so that we can encrypt
# it for them again.
RECIPIENTS=$(gpg --list-packets --list-only $1 | grep keyid | sed 's/^.*keyid//')

# Decrypt the file and place it in the /tmp folder
ENCRYPTED_FILENAME=$(gpg --list-packets "$1" | sed -e '/^:literal data packet:$/!d' \
    -e 'N' \
    -e 's/[^=]*name="//' \
    -e 's/",$//' \
    -e 'q')
if [ -z "$ENCRYPTED_FILENAME" ]
then
  # Filename is empty
  ENCRYPTED_FILENAME=$(sed 's/\.[^.]*$//' <<<$1)
fi
# Check to see if this file already exists.  If it does, warn the user and exit.
if test -f "/tmp/$ENCRYPTED_FILENAME"; then
  zenity --info --title "Warning" --text "Temporary file already exists.  Cannot continue." --icon "$ZENITY_WINDOW_ICON"
  exit
fi
gpg --output "/tmp/$ENCRYPTED_FILENAME" --decrypt "$1"

# Take a hash of the file
CHECKSUM_BEFORE=$(sha256sum /tmp/$ENCRYPTED_FILENAME | cut -f 1 -d " ")

# Open the file with the default editor
filetype=$(xdg-mime query filetype "/tmp/$ENCRYPTED_FILENAME")
editor=$(grep "$filetype" "`dirname \"$0\"`/editors")
rc=$?
editor=$(echo -e "$editor" | cut -f 2)
if [ $rc -eq 1 ]
then
  # String is empty.  No associated editor.  Alert the user.
  zenity --info --title "No Associated Editor" --text "There is no associated editor for this filetype($filetype).  Please add it to `dirname \"$0\"`/editors"
else
  # Open the file
  $editor /tmp/$ENCRYPTED_FILENAME
fi

# Take another hash of the file after editing is complete
CHECKSUM_AFTER=$(sha256sum /tmp/$ENCRYPTED_FILENAME | cut -f 1 -d " ")

# Check to see if the file has changed
if [ $CHECKSUM_BEFORE != $CHECKSUM_AFTER ]
then
  # File has changed
  # Save the file back to its original location
  # Build the encryption command
  ENCRYPTION_COMMAND="gpg --yes --output $1 --encrypt"
  if [ GPG_SIGN ]
  then
    # If automatic signing is turned on, then sign
    ENCRYPTION_COMMAND="$ENCRYPTION_COMMAND --sign"
  fi
  # For each key in $RECIPIENTS, append --recipient [key] to $ENCRYPTION_COMMAND
  while IFS= read -r line
  do
    ENCRYPTION_COMMAND="$ENCRYPTION_COMMAND --recipient $line"
  done <<< "$RECIPIENTS"
  ENCRYPTION_COMMAND="$ENCRYPTION_COMMAND /tmp/$ENCRYPTED_FILENAME"
  $ENCRYPTION_COMMAND

  if [ $? -eq 0 ]
  then
    # Encryption command was successful, delete the temporary file
    rm -f /tmp/$ENCRYPTED_FILENAME
    zenity --info --title "Success" --text "File successfully encrypted" --icon "$ZENITY_WINDOW_ICON"
  else
    zenity --info --title "Failure" --text "Failed to encrypt the file.  The temporary file is located at /tmp/$ENCRYPTED_FILENAME" --icon "$ZENITY_WINDOW_ICON"
  fi
else
  rm -f /tmp/$ENCRYPTED_FILENAME
  zenity --info --title "No Change" --text "No change was made to the file" --icon "$ZENITY_WINDOW_ICON"
fi
