#!/bin/bash

# This script decrypts a file and opens it with the default editor.
# When the program that opened the file is closed, the file is
# checked for any changes.  If no changes have occured, the file
# is simply closed.  If changes occurred, then the file is
# re-encrypted.

filetype=$(xdg-mime query filetype "$1")
editor=$(grep "$filetype" "`dirname \"$0\"`/editors" | cut -f 2)
$editor $1
