#!/bin/bash

if [ -r "`dirname "$0"`/gpg.conf" ]; then
  . "`dirname "$0"`/gpg.conf"
elif [ -r "`dirname "$0"`/../gpg.conf" ]; then
  . "`dirname "$0"`/../gpg.conf"
else
  exit 1
fi

RECIPIENTS=$(_select_public_keys)

if [ -z "$RECIPIENTS" ]; then
  _zenity_info "1" "" "No key selected.  Unable to encrypt file."
  exit 1
fi

# For each key in $RECIPIENTS, append --recipient [key] to $ENCRYPTION_COMMAND
while IFS= read -r line
do
  RECIPIENT_SWITCH="$RECIPIENT_SWITCH --recipient $line"
done <<< "$RECIPIENTS"
set -x
if [ "$?" -eq 0 ]; then
  gpg --output "$1".asc --encrypt --armor $RECIPIENT_SWITCH "$1" 1>> "$OUTPUT" 2>> "$OUTPUT"
  _zenity_info "$?" "Successfully encrypted" "Unknown error (more information can be found at ~/.xsession-errors)"
fi
set +x
